language: node_js
node_js:
- lts/*
sudo: false
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: Zjo7nQKzIfebHmYpkGw+RTXUqgfMDPTQ2M25NNsh+0tsvOTsArvkWyLQDWwe7Swt7A7kiMbVTx5uTyl0wVh+HQ85UWE3M0+atZ10TbuBGAFe2YeomBiMfntUeY6dCjB9mOEPkW+eFvo2nAP6+kEoESu1LJDtvL4kwJ/qSVsOSZQNqkFMk0FNZQJ0k6c4DoPgp+bHXB05fCBL2CbLtTiwYZNP4i/GXfnHPU5IdcaEz83YP0p+KZZrJcqP1OBGP9eKXIMS/Z8Ym2A9JmLbksI6fwQOgGPjnAmbgSUk8Rtf5eQ14gq0TK6Evn6jGE5/OQjyD/7kUOPjrOV2btaTcufgbbNBtqHg+Q63JIGGMPz8KwlKhc/zJp9BInF75m3KdqtVFaimzkgAREJUddz4GrbnXFmICz397h6H4sIWTdG2+jX3Doh9NfqjfRDHoM+Z+jAVvOeQ34/ldPiG2AaXSIyYe0Rm9RJhcNGAm2bD8Je9/n8YVr8QuTvWW7O1U28Fak9FF8PeVvE0dexKPIXNY+Hr5iq9e/EEcxhcbaVa8O7SETzAhJWNO9Xyg0rokP3z5/LS1PlPUsruf7L5MaHneUdkRD//et/nVpHirnJl2Klp/ytg20hGX6k3ZwkJv/HIVFYXxfDPTVHrE0MtceO88a3US9cTJIpVePRbSKMo/0gQX7Q=
  on:
    tags: true
    repo: noflo/noflo-assembly-utils
